### ISSUE TITLE
How do I use

### ISSUE THREAD

**Issue by homerokzam** [dansiegel/Prism.Plugin.Popups#1]
Nice to be your initiative. How do I use it?

Thanks,
Homero

**Comment by homerokzam** [comment]
I got to use it. Very cool!

Do you know the SlideOverKit library? Have you used with Prism? Can I use the same way you did for Rg.Plugins.Popup?

Thanks,
Homero

**Comment by dansiegel** [comment]
I'm not very familiar with that library, however I can add it to my list of plugins to release.

**Comment by homerokzam** [comment]
Ok.

Thanks,
Homero
