### ISSUE TITLE
Prism.DryIoc.Forms 7.2.0.1367 issue with Prism.Plugin.Popups 2.2.0.293

### ISSUE THREAD

**Issue by zinczinc** [dansiegel/Prism.Plugin.Popups#100]
- I started a new Prism.Forms Application from Prism Templates;
- I upgraded everything to Xamarin.Forms 4.1 (vesion 4.1.0.618606);
- I also upgraded Prism.DryIoc.Forms to version 7.2.0.1367
I recompiled and ran the application (MyApp.Droid). Everything worked fine. The main form correctly loaded and displayed the message: Welcome to Xamarin Forms and Prism.

After that, I added Rg.Plugins.Popup (1.1.5.188) Nuget Package to all projects and initialized it in MainActivity as advised 

`    {
        ....
        public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
        {
         protected override void OnCreate(Bundle bundle)
         {
           ...
            base.OnCreate(bundle);

            Rg.Plugins.Popup.Popup.Init(this, bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App(new AndroidInitializer()));
        }
    }
`

Then, I added Prism.Plugin.Popups (2.2.0.293) Nuget Package to all projects and registered it in App (.Net Standard project) like so:

`        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            

            containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<MainPage, MainPageViewModel>();
            containerRegistry.RegisterPopupNavigationService();
        }
`

After that, I upgraded Prism.DryIoc.Forms to the latest stable version (7.2.0.1367) as of this writing.

I ran the application and it crashed with error message "System.MissingMethodException: Method not found: void Prism.Ioc.IContainerRegistryExtensions.RegisterInstance<!0>(Prism.Ioc.IContainerRegistry,!!0)
 " when hitting the Ioc registration line at: 
 
`containerRegistry.RegisterPopupNavigationService();` 

I downgraded Prism.DryIoc.Forms to version 7.1.0.431 and everything worked again.

So I concluded that Prism.DryIoc.Forms 7.2.0.1367 must have an issue when trying to register Prism.Plugin.Popups 2.2.0.293. I have not tried other versions of Prism.Plugin.Popups.

Could you help look into this, please?

**Comment by nyxiscoo1** [comment]
+1
I’m experiencing the same issue after updating prism to 7.2.
Take a look please.

**Comment by nyxiscoo1** [comment]
Updating to 2.4.0.417-pre fixed the issue.

**Comment by dansiegel** [comment]
2.2 was the last stable release which was not built against Prism 7.2... 2.4 was a preview because it was the last build to go out but built against 7.2... I should have an updated build out soon... I'll also be updating the versioning to make it easier to follow so builds will be versioned against what version of Prism it's built against.
