### ISSUE TITLE
Application crash after clicking the transparent background

### ISSUE THREAD

**Issue by gutierrezralph** [dansiegel/Prism.Plugin.Popups#112]
I was successfully installed and implement the required initialization for the plugins nut when I clicked the transparent background, 
![image](https://user-images.githubusercontent.com/26339824/63841057-ac171180-c9b4-11e9-927c-16a4704938e0.png)

I have Error says " System.NotImplementedException: 'The method or operation is not implemented.' ".
![image](https://user-images.githubusercontent.com/26339824/63841112-c51fc280-c9b4-11e9-9cc3-0c93bb05812e.png)

I was trying to look for a click background event but there's no available event like that. 
I using a 7.2.0.573 version.

Any available workaround for this is much appreciated. Thank you

**Comment by dansiegel** [comment]
Can you provide a sample that reproduces this issue.

**Comment by dansiegel** [comment]
@gutierrezralph I am closing this as no reproduction has been provided. If you want to provide a sample that demonstrates the issue we can reopen the issue.
