### ISSUE TITLE
Update Rg.Plugin.Popup to V1.2.0.223

### ISSUE THREAD

**Issue by ricavir11** [dansiegel/Prism.Plugin.Popups#118]
Hi,

Can you please update Rg.Plugin.Popup to version 1.2.0.223 ?
A blocking issue as been fixed to work with iOS 13 : https://github.com/rotorgames/Rg.Plugins.Popup/issues/459 

This update is very important as all apps using Prism.plugin.popups are impacted on iOS (at least if build is done with iOS 13 SDK)

**Comment by trungbq1712** [comment]
confirm that the issue is solved when updating Rg.Plugin.Popup to lastest version

**Comment by lazarnikolov94** [comment]
I can confirm. I just switched to the latest version of Rg.Plugin.Popups 1.2.0.223 and the crashing is gone.

**Comment by dansiegel** [comment]
@ricavir11 I always update Rg.Plugins.Popup (assuming there is an update) when I release updates for this plugin. In the mean time if you are experiencing a bug with Rg.Plugins.Popup I suggest just adding it directly as a dependency to your project to get the update as long as there are no binary incompatibilities you should be fine.
