### ISSUE TITLE
[question] Is this plugin yet necessary ?

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Plugin.Popups#122]
Recently in version 7.2 Prism indroduce a new feateure called "Dialog Service" I've noticed that this library does essentialy the same job of "Dialog Service", my doubt is if this library does anything further that was implemented with "Dialog Service" ?

Thanks

**Comment by dansiegel** [comment]
@candidodmv hopefully the docs help answer why / what is different. The entire point is that from a development experience creating Dialogs is 100% the same as it would be without the Plugin in... if you still need more clarification please let me know and I will try to answer the question https://popups.prismplugins.com/dialogs/

**Comment by candidodmv** [comment]
Thanks @dansiegel your answer was enough to clarify.
