### ISSUE TITLE
Support for IApplicationLifecycleAware delegates

### ISSUE THREAD

**Issue by pravincarvalho** [dansiegel/Prism.Plugin.Popups#123]
If a popup window is open, I noticed that the IApplicationLifecycleAware delegates for the PopupViewModel are not invoked when the application OnSleep and OnResume delegates are invoked. 
The delegates are invoked on the base page that opened the popup.

I looked through the source and it seems like this is not yet implemented. I do think that it is a useful feature to have. Would you like to put it on the roadmap?

**Comment by dansiegel** [comment]
I'll have to think about what the best way to expose this will be. In the mean time you can use this as a work around:

```cs
protected override void OnResume()
{
    if (MainPage != null)
    {
        var page = GetCurrentPage();
        PageUtilities.InvokeViewAndViewModelAction<IApplicationLifecycleAware>(page, x => x.OnResume());
    }
}

protected override void OnSleep()
{
    if (MainPage != null)
    {
        var page = GetCurrentPage();
        PageUtilities.InvokeViewAndViewModelAction<IApplicationLifecycleAware>(page, x => x.OnSleep());
    }
}

private Page GetCurrentPage()
{
    var popupNav = Container.Resolve<IPopupNavigation>();
    return popupNav.PopupStack.LastOrDefault() ?? PageUtilities.GetCurrentPage(MainPage);
}
```

**Comment by dansiegel** [comment]
Support for this will be added shortly. Please note that under no circumstance should you use the PopupPlugin OnResume/OnSleep and call PrismApplication's base implementation. That would result in calling both the correct and incorrect page.

**Comment by pravincar** [comment]
Thanks @dansiegel for getting back on this!
