### ISSUE TITLE
No Page in PopupStack

### ISSUE THREAD

**Issue by mr5z** [dansiegel/Prism.Plugin.Popups#129]
Hi,

We've been experiencing this issue since I posted this: https://github.com/dansiegel/Prism.Plugin.Popups/issues/82

I believe the issues lies with this line:
https://github.com/dansiegel/Prism.Plugin.Popups/blob/bb547ca898e3446de3570dab6aa43135821a1d71/src/Prism.Plugin.Popups/PopupPageNavigationService.cs#L287

From Rg.Plugins.Popup, [they put lock before accessing the list](https://github.com/rotorgames/Rg.Plugins.Popup/blob/5eb2f853bd1b1c4040ea482e288cf555d36f1c0b/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L92-L103)

Maybe you should too?

**Comment by dansiegel** [comment]
closing this as there is no reproduction

**Comment by mr5z** [comment]
> closing this as there is no reproduction

I think this is a valid one although it's from another post but the same issue:

https://github.com/dansiegel/Prism.Plugin.Popups/issues/82#issuecomment-508059506

**Comment by dansiegel** [comment]
@mr5z you didn't provide a reproduction on this issue.
