### ISSUE TITLE
Destroy is not invoked during navigation from PopupPage to a ContentPage

### ISSUE THREAD

**Issue by pravincar** [dansiegel/Prism.Plugin.Popups#156]
While closing a popup page, invokes the Destroy method, navigating from a modal page to a new content page closes the modal page without firing the Destroy method.
This leaves allocated resources and event handlers around since the Destroy method is intended to clean up these resources.

This issue has been observed with the following version
Prism.Plugin.Popups : 7.2.0.1046
Rg.Plugins.Popup: 2.0.03

A full reproduction has been attached
1. Click the button "Open Modal Page"
2. Click the button "Go to second page"

**Expected**
Destroy should be fired for the ModalPageViewModel

**Actual**
The destroy handler is not invoked

[PrismPopupBug.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/5014498/PrismPopupBug.zip)

**Comment by dansiegel** [comment]
This is fixed and available in the Sponsor feed at SponsorConnect

**Comment by pravincar** [comment]
@dansiegel Thanks!
