### ISSUE TITLE
While using accessibility(TalkBack) on popups on Android, Focus also goes to background view.[Bug] 

### ISSUE THREAD

**Issue by HirakCTS** [dansiegel/Prism.Plugin.Popups#169]
I am using popups in Android. While i turned on accessibility, focus of TalkBack also goes to dimmed background view. It supposed to stay on the popup only.
Expected Behavior - Focus supposed to stay on popup view only
Actual Behavior - Focus goes to background view as well. Breaking functionality of accessibility.

[Refer this](https://github.com/xamarin/Xamarin.Forms/issues/12251)

**Comment by dansiegel** [comment]
@HirakCTS it would seem that your issue is with [Rg.Plugins.Popup](https://github.com/rotorgames/Rg.Plugins.Popup). The Prism.Plugin.Popups is only a thin wrapper to help Prism applications seamlessly utilize Rg.Plugins.Popup.
