### ISSUE TITLE
When Prism 8 Release update in Nuget ?

### ISSUE THREAD

**Issue by NamCkiku** [dansiegel/Prism.Plugin.Popups#179]
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    // This updates INavigationService and registers PopupNavigation.Instance
    containerRegistry.RegisterPopupNavigationService();
}
Crash with Prism 8

**Comment by dansiegel** [comment]
The package is available in the Sponsor Connect CI feed. I will release to NuGet when I feel it is ready for public release.
