### ISSUE TITLE
 An unexpected error occurred while resolving 'Prism.Navigation.INavigationService' 

### ISSUE THREAD

**Issue by kerbooo** [dansiegel/Prism.Plugin.Popups#187]
Hello, I am using **Prism Forms **8.0.1909.**** After adding as following line for using **Prism.Plugin.Popups **7.2.0.1046**** 

```
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
	containerRegistry.RegisterPopupNavigationService();
	....
}
```

I am getting as following error
`
Prism.Ioc.ContainerResolutionException: 'An unexpected error occurred while resolving 'Prism.Navigation.INavigationService''`

After remove `containerRegistry.RegisterPopupNavigationService();` line, I am not getting any error but popup pages do not works.

Thank you in advance for your help.

**Comment by dansiegel** [comment]
These two packages are not compatible. The Popup Plugin for v8 has not yet been released to NuGet.org. A compatible package is however available on SponsorConnect.
