### ISSUE TITLE
Mono.Linker.MarkException in Release mode android

### ISSUE THREAD

**Issue by jitendrajadav** [dansiegel/Prism.Plugin.Popups#189]
I have install "Prism.Plugin.Popops" and trying to deploy my build on to device in release mode but it is not successfully build I am getting error like below.

How to reproduce:
1. Create Xamarin.Forms application.
2. Add Prism packages from NuGet including Rg.Plugins.Popup
3. changes you debug mode to release and try to build it.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Void Prism.Navigation.PopupExtensions/<ClearPopupStackAsync>d__7::MoveNext()' in assembly: 'Prism.Plugin.Popups.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<Prism.Navigation.INavigationResult> Prism.Navigation.INavigationServiceExtensions::GoBackAsync(Prism.Navigation.INavigationService,Prism.Navigation.INavigationParameters,System.Nullable`1<System.Boolean>,System.Boolean)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	KegID.Android			
`

Sample code
[kegid-x.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/5688665/kegid-x.zip)

Environment info:

Microsoft Visual Studio Professional 2019 Preview
Version 16.9.0 Preview 2.0
VisualStudio.16.Preview/16.9.0-pre.2.0+30803.129
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA694
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

C# Tools   3.9.0-2.20602.2+eb0a7ff1c241695e17b07b096593804fdd5cfcfd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

SQL Server Data Tools   16.0.62011.24130
Microsoft SQL Server Data Tools

Xamarin   16.9.000.196 (main@7f5b5b9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.105 (remotes/origin/c2adbf832aee3f27874ac90b17c433d311053b06@c2adbf832)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.41 (0d792de)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.99.218 (master/9bc0003)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: ac59637
    Java.Interop: xamarin/java.interop/master@99897b2
    ProGuard: Guardsquare/proguard/v7.0.0@84e8560
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

Xamarin.iOS and Xamarin.Mac SDK   14.9.0.27 (f4c9327fa)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by ErickSilva2605** [comment]
would anyone have a solution for this?

**Comment by dansiegel** [comment]
The solution is simple... don't use the 7.2 version of Prism Popups with Prism 8... they are binary incompatible.
