### ISSUE TITLE
Release version 8 to be compatible with prism 8

### ISSUE THREAD

**Issue by developer9969** [dansiegel/Prism.Plugin.Popups#191]
Hi
It is my understanding that if you are using prism 8 you need the latest version of this plugin and version 7.2 is not compatible.

We have not been able to upgrade to prism 8 and starting using regions for this reason.

Is this true?

if so is there any plans to release to the public?

many thanks

p.s 
did ask my company to sponsor you guys I will find out after the holidays.

**Comment by dansiegel** [comment]
You are correct if you are using Prism 8 you would need the v8 version of this plugin which is currently only available to Enterprise Support customers and GitHub Sponsors. 

The short answer is yes I do plan on releasing v8 of this plugin to NuGet.org. I do not have a planned date as it ultimately comes down to when I have the time to deal with some of the outstanding issues.

**Comment by developer9969** [comment]
thanks for your reply, hopefully It won't be long :)

**Comment by dansiegel** [comment]
a beta version has been released to NuGet
