### ISSUE TITLE
Xamarin.Forms.WPF - Strong Name Issue

### ISSUE THREAD

**Issue by UweReisewitz** [dansiegel/Prism.Plugin.Popups#196]
Hi,
I've tried to use Prism.Plugin.Popups with Xamarin.Forms.WPF.
When using 7.2.0.1046 I get the following exception:
public App(IPlatformInitializer initializer)
            : base(initializer)
        {
        }
System.IO.FileLoadException
  HResult=0x80131044
  Message=Die Datei oder Assembly "Prism.Forms, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Eine Assembly mit starkem Namen ist erforderlich. (Ausnahme von HRESULT: 0x80131044)
 (Translation: Strong Name Assembly is required)

When using 8.0.31-beta I get the following when compiling my Xamarin.Forms.WPF project:
Unknown build error, 'Could not load file or assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'	

It seems that there is a strong name assembly somewhere in the call stack.

Am I missing something here?

**Comment by dansiegel** [comment]
Prism.Core, & Prism.Wpf are all strongly named assemblies... for Prism.Forms there is no reason for it to be strongly named. Also since you haven't provided a reproduction of the issue I can't really do anything to look into what your issue is.

**Comment by UweReisewitz** [comment]
I'm sorry. Of course I should have done this first.

I have created the following repository to showcase the problem:
https://github.com/UweReisewitz/PluginPopups
It contains the most basic  Xamarin Forms Prism application (Implementation and WPF project). It curently uses 7.2.0.1046 of the Prism.Plugin.Popups. It compiles fine but fails at runtime with the error mentioned above.
If I comment out containerRegistry.RegisterPopupNavigationService(); in WPFInitializer the application runs.

I hope this helps to reproduce the problem. I apologize for not creating this in the first place.

BTW, when switching to 8.0.31-beta, I'm unable to build the application at all. It fails during compile with the compiler error mentioned in my first message.

**Comment by UweReisewitz** [comment]
PopupPageNavigationService derives from PageNavigationService which is defined in Prism.Forms.

Prism.Plugin.Popups is a strong named assembly, Prism.Forms is not. Therefore Prism.Plugin.Popups is unable to laod this assembly.

Makes sense?
