### ISSUE TITLE
Error on Prism 8.0.0.1909 Prism.Plugin.Popups 7.2.0.1046

### ISSUE THREAD

**Issue by mibuswolf** [dansiegel/Prism.Plugin.Popups#198]
[error.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/5928741/error.zip)

 protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
          
            containerRegistry.RegisterSingleton<IAppInfo, AppInfoImplementation>();
            containerRegistry.RegisterPopupNavigationService();
           
            containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<MainPage, MainPageViewModel>();
            containerRegistry.RegisterForNavigation<SamplePopup, SamplePopupViewModel>();
         
        }

<?xml version="1.0" encoding="utf-8" ?>
<popups:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:popups="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:prism="http://prismlibrary.com"
             x:Class="BlankApp3.Views.SamplePopup">
             
        <StackLayout BackgroundColor="White"
            VerticalOptions="Center" HorizontalOptions="Center" Padding="20">
            <Label Text="Welcome to Xamarin.Forms!"/>
        <Button Text="cloase" Command="{prism:GoBack}"/>

    </StackLayout>
   
</popups:PopupPage>

When I am running the app in degub mode it throws me the following error

Prism.Ioc.ContainerResolutionException: 'An unexpected error occurred while resolving 'Prism.Navigation.INavigationService''

**Comment by dansiegel** [comment]
Those two package versions are binary incompatible... you will need to use the v8 version of the Popup plugin if you're targeting Prism 8.
