### ISSUE TITLE
Destroy not called on PopupPages that implement IDestructible

### ISSUE THREAD

**Issue by mackayn** [dansiegel/Prism.Plugin.Popups#2]
HI,

Firstly this is a really useful pluggin that allowed us to easily integrate Rx.Popup into our Prim app.

The issue I have is that in Prism 6.3 beta they added IDestructible to allow you to cleanup attached behaviors in controls.

This is the scenario I'm hitting, when popping the PopupPage Destroy is never called on the Page

```
using Prism.Navigation;
using Rg.Plugins.Popup.Pages;

namespace Foobar.Views
{
    public partial class FleetPopupPage : PopupPage, IDestructible
    {
        public FleetPopupPage()
        {
            InitializeComponent();
        }

        public void Destroy()
        {
            ListviewFav.Behaviors.Clear(); // Never called
        }
    }
}
```
Does the pluggin support IDestructible? It's a really useful feature in 6.3.

In the interim I've done the cleanup in OnDisappearing but the page lifecycle events in forms are currently a bit hit or miss and triggering an intent or something my trigger this code. Hopefully the proposed changes to Forms will be implemented to make cleanup a little easier soon.

**Comment by dansiegel** [comment]
I agree that would be a really good addition. I'll try to get a preview out in the next day or two.

**Comment by mackayn** [comment]
Thanks.

**Comment by dansiegel** [comment]
Sorry for the delay, the 1.1.0-pre1 package is now available. Look for a pre2 drop when Prism releases 6.3.0-pre2, that will introduce support for using either the `INavigatedAware` or `INavigatingAware` interfaces on your ViewModels or Pages.

**Comment by mackayn** [comment]
Hi Dan,

I tested 1.1.0-pre1 and it works as expected with IDestructible.

Many thanks for looking into this.

**Comment by mackayn** [comment]
Hi Dan,

I found an unwanted side effect.

While it does trigger Destroy on the Popup page when you implement IDestructible, it also triggers Destroy in the master detail page, I only noticed because I could no longer select my listitems in the master Popover list.

Works as expected.

```
using Prism.Navigation;
using Rg.Plugins.Popup.Pages;

namespace MarineOps.Views
{
    public partial class FleetPopupPage : PopupPage, IDestructible
    {
        public FleetPopupPage()
        {
            InitializeComponent();
        }

        public void Destroy()
        {
            ListviewFav.Behaviors.Clear();
        }

    }
}
```

Triggers unexpectedly
```
namespace MarineOps.Views
{
    public partial class AppMasterDetailPage : MasterDetailPage, IDestructible
    {
        public AppMasterDetailPage()
        {
            InitializeComponent();
        }

        public void Destroy()
        {
            // BUG: This is been fired when the popup page closes
            //ListviewShell.Behaviors.Clear();
        }

        private void ImageButton_OnItemTapped(object sender, EventArgs e)
        {
            IsPresented = false;
        }
    }
}
```
