### ISSUE TITLE
Orientation Changes Do Not Update PopupView Layout

### ISSUE THREAD

**Issue by Axemasta** [dansiegel/Prism.Plugin.Popups#215]
I noticed that when my device orientation changed whilst a popup was presented the popup was not being displayed correctly. A completely centered view will become offset after the device orientation changes.

```
<AbsoluteLayout HorizontalOptions="Center" VerticalOptions="Center">
    ...
</AbsoluteLayout>
```

I have recreated the issue and it appears to be due to using Prism 8.0.0.1909 + Beta 8.0.31-beta. The same project with Prism 7 behaves as expected & updates the view when orientation changes:

Recreation Steps:

- Download sample code ([Orientation Popup Recreation.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/6405108/Orientation.Popup.Recreation.zip))
- Build & run on iOS
- Press "Show Popup"
- Popup displays in the center
- Change device orientation

Expected Behaviour:
Screen content orients and popup is displayed in the center of the screen

Actual Behaviour:
- Popup is not centered and instead positioned relative to original orientation
- `OnSizeAllocated` does not get called

- Downgrade NuGet versions:
  - Prism.DryIoc.Forms 8.0.0.1909 => 7.2.0.1422
  - Prism.Plugin.Popups 8.0.31-beta => 7.2.0.1046

Screenshots:

| Version | Horizontal                                                                                                        | Vertical                                                                                                         |
|---------|-------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|
| 7.*     | ![7 Horiz](https://user-images.githubusercontent.com/33064621/116691195-647b3100-a9b2-11eb-95c7-14f252831008.png) | ![7 Vert](https://user-images.githubusercontent.com/33064621/116691218-6cd36c00-a9b2-11eb-9d3e-e18aca2cc2e3.png) |
| 8.*     | ![8 Horiz](https://user-images.githubusercontent.com/33064621/116690754-c25b4900-a9b1-11eb-9622-4cb9dbab5396.png) | ![8 Vert](https://user-images.githubusercontent.com/33064621/116690760-c5563980-a9b1-11eb-8455-e8fbe7770429.png) |

To make sure this wasn't an issue with my xaml views, I tried adding them to a vanilla rg popups project (their github sample) and the page resizing / orientation worked as I'd expect.

In my sample code I include a content page / popup page extension that fires events for orientation changed. In the older versions this method is fired correctly:
![Orientation Calls](https://user-images.githubusercontent.com/33064621/116691623-f7b46680-a9b2-11eb-9a05-733df91da6d5.png)

And does not get fired in the latest versions, except when the view is initialised

Obviously not a major issue but does make popups look a bit jarring when the device orientation changes, since `OnSizeAllocated` is not being called, I assume something inbetween the object & rg is altering the behaviour and suppressing this event from bubbling up, causing the view not to be updated. I'm happy to help with any fixes required :)

**Comment by dansiegel** [comment]
> its working on the latest sponsor connect build, the issue isnt there in 8.0.73

Closing as this was solved in the CI feed. If the latest release breaks this please let me know.
