### ISSUE TITLE
[Regression] LinkAll 

### ISSUE THREAD

**Issue by RadoslawKubas** [dansiegel/Prism.Plugin.Popups#217]
After update to 8.0.76  #77 returned. It was fine in 8.0.31-beta.

**Comment by dansiegel** [comment]
you should be able to add a linker config to preserve the Popup Plugin.

**Comment by RadoslawKubas** [comment]
Yes, thank you, with linker it works perfect, just wanted to report the change.

**Comment by dansiegel** [comment]
appreciate you letting me know. Moving forward this responsibility is on the developer to manage with the Linker config
