### ISSUE TITLE
PopUp Page Won't Navigate Twice

### ISSUE THREAD

**Issue by kylewarren** [dansiegel/Prism.Plugin.Popups#41]
From Page A, I click button and call navigationService.NavigateAsync("popuppage");

From popuppage, I call navigationService.GoBackAsync();

I'm back at Page A, but if I try to click button and call popuppage again nothing happens.

I have to leave Page A and go back to Page and then I can call popup again.

**Comment by dansiegel** [comment]
@kylewarren what version are you using?

**Comment by kylewarren** [comment]
2.0.0-pre1.

**Comment by dansiegel** [comment]
as a work around you can use `PopupGoBackAsync ` until this is fixed.

**Comment by dansiegel** [comment]
this seems to be caused by issue #46.
