### ISSUE TITLE
build issue: when using Prism.Plugin.Popups.DryIoc  using Container.RegisterPopupNavigationService() in  RegisterTypes blocks compile

### ISSUE THREAD

**Issue by mdonogma** [dansiegel/Prism.Plugin.Popups#43]
Using the Prism master detail example. It leverages Prism.Plugin.Popups.DryIoc for IOC.
added : Prism.Plugin.Popups.DryIoc to the project. (see link below)

The landing page on this site indicates Prism.Plugin.Popups.DryIoc is supported however when using it the project will not compile?
Here is the Xamarin forms hamburger menu project used: https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/HamburgerMenu

extract from class App : PrismApplication
                  protected override void RegisterTypes() 
	         { 
				 Container.RegisterPopupNavigationService();  //This line fails indicate method does not exist. (
		 }

**Comment by dansiegel** [comment]
What version are you using?

**Comment by mdonogma** [comment]
Prism.Forms 6.3.0
Prism.DryIoc.Forms 6.3.01
Prism.Plugin.Popups.DryIoc version 1.1.0
Rg.Plugins.Popup 1.0.4

**Comment by dansiegel** [comment]
Notice that there are instructions for version 1 .x and version 2.x. `Container.RegisterPopupNavigationService()` does not exist in v1.x.

https://github.com/dansiegel/Prism.Plugin.Popups#version-2x

https://github.com/dansiegel/Prism.Plugin.Popups#version-1x
