### ISSUE TITLE
Receiving parameters from PopupGoBackAsync

### ISSUE THREAD

**Issue by MartinRobins** [dansiegel/Prism.Plugin.Popups#45]
Version 1.1 for DryIoc.

I am calling "PushPopupPageAsync" from within a ViewModel and then from within the ViewModel of the popup I am calling "PopupGoBackAsync". Both calls are being passed parameters and I have implemented INavigatedAware on each of the ViewModel classes.

The call to "PushPopupPageAsync" results (correctly) in the "OnNavigatedTo" of the popup ViewModel being called so that I can receive the parameters passed to the popup. The call to "PopupGoBackAsync" however does not result in "OnNavigatedTo" being called in the original (calling) ViewModel so I am unable to receive the result from the popup.

		protected async Task ExecuteSelectCommand() {
			if (CanExecuteSelectCommand(SelectedRoute)) {

				NavigationParameters parameters = new NavigationParameters {
					{ nameof(Route), SelectedRoute.RouteID }
				};

				await this.NavigationService.PopupGoBackAsync(parameters);

			}

		}

What am I doing wrong?

As far as I can see from the source (as it currently stands, part way through the migration to v2), "OnNavigatedTo" should be called upon return to the original form with the parameters that I passed to "PopupGoBackAsync".

Thanks.

**Comment by MartinRobins** [comment]
Ok, I think I have identified the problem...

I am using a MyMasterDetailPage/NavigationPage/MyContentPage navigation structure where MyMasterDetailPage is inherited from MasterDetailPage and MyContentPage is inherited from ContentPage but NavigationPage is the original Xamarin.Forms.NavigationPage.

Within the shared implementation of the PopupExtensions class, the "FilterPage" method is used to try and determine the page/binding context  to which the INavigatedAware calls should be made. This method uses the TypeInfo.IsSubclassOf method to determine the type of page that is being dealt with in order to "walk" the navigation and get to the current page...

	var pageTypeInfo = page.GetType().GetTypeInfo();
	while (pageTypeInfo.IsSubclassOf(typeof(MasterDetailPage)) ||
				pageTypeInfo.IsSubclassOf(typeof(NavigationPage)) ||
				pageTypeInfo.IsSubclassOf(typeof(MultiPage<>))) {
		if (page.GetType().GetTypeInfo().IsSubclassOf(typeof(MultiPage<>))) {
			page = (page as MultiPage<Page>).CurrentPage;
		}
		else if (page.GetType().GetTypeInfo().IsSubclassOf(typeof(MasterDetailPage))) {
			page = (page as MasterDetailPage).Detail;
		}
		else if (page.GetType().GetTypeInfo().IsSubclassOf(typeof(NavigationPage))) {
			page = (page as NavigationPage).CurrentPage;
		}
		pageTypeInfo = page.GetType().GetTypeInfo();
	}

Because my implementation uses the Xamarin.Forms.NavigationPage directly, the part of the test above that is checking for NavigationPage fails (it is not a subclass) and therefore the method determines that the NavigationPage is in fact the current page and as such this becomes the target for INavigatedAware; of course, it is not supported on that page and therefore no call is made. In reality, the page that should have been the target for INavigatedAware is NavigationPage.CurrentPage (or "MyContentPage" in this example).

I do not think this is the intended behaviour (I am making this assumption based upon the behaviour of the Prism navigation service) but you should correct me if I am wrong.

Resolving the problem, at least in my scenario, is not difficult however if such a change were to be accepted into the project it would potentially be a breaking change for any other users who have become dependent on the current functionality (though I am not entirely certain that this can be the case as the problem does not occur if working with a subclass of NavigationPage and the standard NavigationPage cannot be targeted as it does not support INavigatedAware).

Based upon my belief that the project is currently Visual Studio 2013/C#6, I propose that the code shown above be replaced with the following...

	while (page is MultiPage<Page> || page is MasterDetailPage || page is NavigationPage) {
		if (page is MultiPage<Page>) {
			page = (page as MultiPage<Page>).CurrentPage;
		}
		else if (page is MasterDetailPage) {
			page = (page as MasterDetailPage).Detail;
		}
		else if (page is NavigationPage) {
			page = (page as NavigationPage).CurrentPage;
		}
	}

Alternatively, the Visual Studio 2017/C#7 option would be to replace the same code with the following...

	while (page is MultiPage<Page> || page is MasterDetailPage || page is NavigationPage) {
		switch (page) {
			case MultiPage<Page> multiPage:
				page = multiPage.CurrentPage;
				break;
			case MasterDetailPage masterDetailPage:
				page = masterDetailPage.Detail;
				break;
			case NavigationPage navigationPage:
				page = navigationPage.CurrentPage;
				break;
		}
	}

Unfortunately, there are no tests within the solution so I am not in a position to determine whether or not such a change would have any other detrimental effect on existing users.

Martin.

**Comment by dansiegel** [comment]
@MartinRobins thanks for reporting this issue. C# 7 wasn't available cross platform when I last published. I do believe refractoring this to C# 7 would likely fix the bug without breaking the current functionality. I should have some time to circle back to this once we ship the Prism 7 preview

**Comment by MartinRobins** [comment]
@dansiegel I do not think that simply upgrading to C# 7 will resolve the issue you need to remove the dependency on TypeInfo.IsSubclassOf(Type) in order to actually fix it (in my scenario). The various C#6/C#7 options I provided are merely syntactic sugar.

**Comment by dansiegel** [comment]
Again I'll take a look at it, in the mean time I might suggest just creating a Page that inherits from NavigationPage until the issue can be resolved.

**Comment by MartinRobins** [comment]
No hurry; I have a local copy of the project with the fix already applied and I am using that for now. I will bring your own version back in when you have the time to address it. Thanks.

**Comment by beylkhanovdamir** [comment]
@dansiegel 
@MartinRobins 

the same problem for me.
could you notify when you can try fix this issue with receiving params from popup? thx

**Comment by MartinRobins** [comment]
@beylkhanovdamir Why not follow Dan's suggestion by simply create a class of your own inheriting from NavigationPage and then using that in the place of your existing NavigationPage; that then bypasses the problem as the class being inspected passes the test of "IsSubclassOf(typeof(NavigationPage))". It saves waiting.

**Comment by beylkhanovdamir** [comment]
@MartinRobins @dansiegel 

yes, but other my page params (which are passed to this page) will be reset after closing popup, and in result, I will have only last passed param from popup. it's not good.

I'm using v1.1.0

**Comment by dansiegel** [comment]
I am looking to remove the extension methods in favor of providing a NavigationService that will handle Pushing and Popping PopupPages. If you continue to have the issue in v2 (once I release the next preview) please let me know.
