### ISSUE TITLE
NavigationService.GoBackAsync() clears calling BindingContext

### ISSUE THREAD

**Issue by AllDayer** [dansiegel/Prism.Plugin.Popups#46]
Apologies if this is too vague. I've noticed that calling 
`await m_NavigationService.GoBackAsync();`
From the pop up view model will set the `BindingContext `of the view that calls it to null.

However using 
`m_NavigationService.PopupGoBackAsync();`
Works fine.

I'm using Prism 6.3
Rg.Plugins.Popup 1.1.0-pre2

**Comment by dansiegel** [comment]
What version of the plugin are you using? The goal of v2 is to eliminate the extension methods, but the current preview has some known bugs that will be addressed in the next preview. Right now I suggest using the 1.1 release, in which case to go back from a PopupPage you need to call `PopupGoBackAsync`

**Comment by AllDayer** [comment]
I'm using Prism.Plugin.Popups.DryIoc 2.0.0-pre1.

Thanks for your help.

**Comment by dansiegel** [comment]
For now I would suggest using the extension as it's more stable. I'll leave this open for now so that it can be investigated as part of the v2 release.

**Comment by satputerohan** [comment]
I am having same issue with Unity version. My views just disappear after I call GoBackAsync. Which extension are you suggesting? I would like a quick resolution on this, as it is unusable with this bug. Doesn't matter if it is a dirty hack for the time being. Thanks :)

**Comment by satputerohan** [comment]
I tried downgrading to 1.1, but it is not calling the OnNavigatedTo of the calling page (tabbedPage) on GoBackAsync(). It only calls OnNavigatedFrom of popup page.

**Comment by dansiegel** [comment]
It should call the active child of a TabbedPage, it will not call OnNavigatedTo on the TabbedPage

**Comment by satputerohan** [comment]
That's what I meant. It is not calling the OnNavigatedTo of the active tab. I am using Prism 6.3 with v1.1 of this library.

**Comment by satputerohan** [comment]
On the contrary, I just checked and I am getting the callback to my TabbedPage, instead of the active tab. This is something I discussed with Bryan Lagunas on [this xamarin forum](https://forums.xamarin.com/discussion/comment/268694#Comment_268694) page .  The callback system is a little inconsistent when the tabs are generated via bindings dynamically vs predefined.

**Comment by dationguyen** [comment]
Hi guys,
Is there any way to keep the page in the cache when we navigating back? 
I want to keep my popup page as a static page. so the ViewModel will be the same when we push the popup again
In the current stage, the Popup page ViewModel will stay there and will be deconstructed (then create another new ViewModel) when we push the popup again.

Hope my English wasn't too bad
Best regards,
Dat Nguyen

**Comment by dansiegel** [comment]
@dationguyen Singleton Views/ViewModels are not supported with Prism, particularly as they cause more problems than they solve.

**Comment by dationguyen** [comment]
Thank @dansiegel!
I will try using the singleton services from the DI.
Is it better?

**Comment by dansiegel** [comment]
this issue has been fixed and will be released soon.
