### ISSUE TITLE
GoBackAsync() make losing all bindable object in the previous page

### ISSUE THREAD

**Issue by dationguyen** [dansiegel/Prism.Plugin.Popups#48]
Hi Guys,
There is a small error when using _navigationService.GoBackAsync, the previous page will lose all of its binding content (all of the binding objects is not appear, the binding context still there )
I switched to _navigationService.PopupGoBackAsync() and it works as normal.

I am using Prism.Plugin.Popups version 2.0 pre.
Hope it helps.
Dat Nguyen

**Comment by dansiegel** [comment]
This is a known issue in 2.0.0-pre1 see #46
