### ISSUE TITLE
Abstract the popup functionality and add it to Prism.Forms?

### ISSUE THREAD

**Issue by opcodewriter** [dansiegel/Prism.Plugin.Popups#50]
Useful stuff, have you considered abstracting the popup functionality and making a PR to Prism.Forms?
It would be useful to have the popup support baked right in Prism.Forms.
By abstracting the popup functionality I mean make it able to work with an adapter for Rg.Plugin.Popup or any other popup functionality.
Not sure if it make sense,..

**Comment by dansiegel** [comment]
I'm not sure that any part of this would be appropriate for Xamarin Forms... if anything were to be brought into Xamarin Forms it would be Rg.Plugin.Popup in which case support for Popups would be integrated directly into Prism.Forms

**Comment by opcodewriter** [comment]
Why wouldn't popups be "appropriate" for Xamarin Forms? 
Maybe I didn't explained it right...
Let me put it this way: if I were to implement my own popup functionality (similar to Rg.Plugin.Popup) how do I make Prism.Forms work with it? I'd have to create something similar to your Prism.Plugins.Popups. So instead of creating Prism.Forms plugins to work with specific popup libraries, I was thinking have a way in Prism.Forms to support popups, but without actually implement showing a popup, because definitely it's not the purpose of Prism to implement this kind of feature.

**Comment by dansiegel** [comment]
If you put together your own Popup library I'm happy to do what I can to abstract things to work across libraries, but there's not much point in trying to abstract it at the moment as it's simply implementing Prism's INavigationService to work with Rg.Plugins.Popup
