### ISSUE TITLE
Prism 7 pre4 breaks Plugin

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism.Plugin.Popups#51]
There are two major breaking changes in Prism 7.0.0.269-pre (pre4) that break the Popups Plugin

1. Navigation Service ctor changed to include the new IPageBehaviorFactory. This breaks the v2 preview
1. NavigationParameters changed how the NavigationMode is stored. There is no way in pre4 to set the NavigationMode.

The next preview of the Popup Plugin cannot be released until there is a new Prism Forms preview/RTM package.

**Comment by rastreus** [comment]
Were these two breaking changes fixed with Prism 7 pre5?

**Comment by dansiegel** [comment]
Pre4 honestly hosed this plugin. Pre5 did contain some fixes that allow me to work with the changes in Prism 7. I even have those fixes done. However, I’m having some tooling issues on the build server that are keeping me from releasing an update. I hope to have something out this week though.

**Comment by dansiegel** [comment]
I should add that the container specific packages will all be deprecated in the next release as Prism 7 has abstracted IOC, which makes it possible to share between all containers.

**Comment by dansiegel** [comment]
fixed in pre4
