### ISSUE TITLE
Popup isn't pushed with Popup Navigation in NavigationPage

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism.Plugin.Popups#52]
When pushing a PopupPage from a child of a NavigationPage, the PopupPage is pushed to the NavigationPage rather than the PopupStack

**Comment by cassionandi** [comment]
The same happens here.

**Comment by cassionandi** [comment]
Dan, maybe the PushAsync must be change to PushPopupAsync...

`protected override Task DoPush(Page currentPage, Page page, bool? useModalNavigation, bool animated, bool insertBeforeLast = false, int navigationOffset = 0)
        {
            switch (page)
            {
                case PopupPage popup:
                    return _popupNavigation.PushAsync(popup, animated);
                default:
                    return base.DoPush(currentPage, page, useModalNavigation, animated, insertBeforeLast, navigationOffset);
            }
        }`

**Comment by dazinator** [comment]
@cassionandi 

Doesn't `_popupNavigation.PushAsync` refer to this: https://github.com/rotorgames/Rg.Plugins.Popup/blob/24ef7a828144af86b98fecf0dbf28840ab5c846d/src/Rg.Plugins.Popup/Contracts/IPopupNavigation.cs

There is no PushPopupAsync method on IPopupNavigation

By the way, I am also trying to get this to work. I have navigated from a `Master / Detail` and my detail is a `TabbedPage`. I am attempting to navigate from the TabbedPage to a popup - and at the moment my navigate call jus't doesn't appear to do anything.

**Comment by cassionandi** [comment]
@dazinator I was expecting the use of some extension that makes PushPopupAsync available. 

If you get you case to work, let us know.

**Comment by dansiegel** [comment]
@cassionandi the PopupNavigationService is checking to see whether it's a PopupPage or not... if it is, it uses the IPopupNavigation to push the page otherwise it defers back to the default Prism behavior.

**Comment by dazinator** [comment]
@cassionandi  I have got this to work now.

As usual, the problem was.. I made a wrong assumption..

I have a `MainApplication` class, and I thought initialising RG Popups in there was as good as initialising it in MainActivity. Don't do this in MainApplication:


```
  Rg.Plugins.Popup.Popup.Init(this, null);
```

Once I moved that into MainActivity instead, it all started working:

```
  Rg.Plugins.Popup.Popup.Init(this, savedInstanceState);
```

**Comment by cassionandi** [comment]
may page is a PopupPage, look:

using Rg.Plugins.Popup.Pages;
public partial class NewVersionPopupPage : PopupPage

<?xml version="1.0" encoding="UTF-8"?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="App.Core.Views.NewVersionPopupPage"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
    CloseWhenBackgroundIsClicked="false"
    >

It works if I use the Xamarin Forms + Rg.Plugins.Popup Navigation.

**Comment by cassionandi** [comment]
Don't know if it helps, but registering or not in the container I got the same result

containerRegistry.RegisterPopupNavigationService(); //commented or not, same result.

**Comment by dansiegel** [comment]
@dadhi This issue appears to only exist when using DryIoc. There is a problem with DryIoc in which the named service is not being replaced, even if you directly get the container, unregister INavigationService and provide a new implementation.

**Comment by cassionandi** [comment]
I'm using DryIoc on my project where this issue happens.

**Comment by dadhi** [comment]
@dansiegel, The only case coming to my mind, if `INavigationService` is already injected in some consumer service. 

In this case, and if you are specifically designing to replace already injected dependency, you need to add to dependency registration:

`setup: Setup.With(asResolutionCall: true)`

Here is why: https://bitbucket.org/dadhi/dryioc/wiki/UnregisterAndResolutionCache

**Comment by dadhi** [comment]
Or you may use `UseInstance` method  which was designed for such cases.

**Comment by dansiegel** [comment]
@dadhi `INavigationService` is registered by Prism by `PrismApplicationBase.RegisterRequiredTypes`, additional registrations are done for the PlatformInitializer (if it exists), and then the user's App... it isn't until after that, that Resolve is ever called. If you look at the sample app the PopupNavigationService is registered in `App.RegisterTypes`. Also `UseInstance` cannot be used as `INavigationService` is a transient service.

**Comment by dansiegel** [comment]
I've added a workaround fix that will work with the current release of Prism.

**Comment by cassionandi** [comment]
Thank you @dansiegel 
It is already available on nuget packages?

**Comment by dansiegel** [comment]
@cassionandi it will be up in the next few hours

**Comment by cassionandi** [comment]
I've just opened an issue to discuss an error on this new version. Thank you anyway.
