### ISSUE TITLE
Android build error with Prism 7.0

### ISSUE THREAD

**Issue by LGFox** [dansiegel/Prism.Plugin.Popups#53]
Hi @dansiegel!

After updating to Prism 7.0 I got a build error:

`Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Microsoft.Practices.Unity.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	OomaSetup.Droid`	

I'm using Unity IoC.
"Prism.Unity.Forms 7.0" uses Unity 5. As I know, Unity 4 and 5 have breaking changes. Prism 6 and 7 have breaking changes too. You're using "Prism.Unity.Forms 6.3" in the project which uses Unity 4.

app.config->BindingRedirect doesn't work for me. I believe it's because your project uses "Prism.Unity.Forms 6.3". But the strange point is that I don't see such error for iOS.

I [added a sample project](https://github.com/LGFox/Prism-Samples-Forms) so you can check it by yourself.
As I believe, you just need to update Prism.Unity.Forms and Xamarin.Forms. )))

**Comment by dansiegel** [comment]
You cannot use v1 with Prism 7. Please update to the latest preview of v2

**Comment by johnfurog** [comment]
hi @dansiegel 

> You cannot use v1 with Prism 7. Please update to the latest preview of v2

 what do you mean on You cannot user v1 ? which package is it ?

**Comment by dansiegel** [comment]
Prism 7 uses Unity 5 which is completely incompatible with previous version. Since version 1 of this plugin was built against Prism 6.3 it makes it completely incompatible with Prism.Unity.Forms. It may work and I stress MAY... for DryIoc and Autofac, however I strongly advise that you use v2 there are a lot of improvements starting with the fact that Navigation is no longer done through an extension method but via the actual Navigation Service.

**Comment by shashikant0423** [comment]
Hi @dansiegel 

I have the issue with the latest version of **Prism.Unity.Forms- 7.0.0.396** , Can you please suggest me how to solve, it's fine for iOS and error to occur only for Android 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'. Perhaps it doesn't exist in the Mono for Android profile? File name: 'Microsoft.Practices.Unity.dll' at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x0009a] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:229 at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:179 at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x0014a] in <96027da06dd5411688a31011072e256f>:0 at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x00237] in <96027da06dd5411688a31011072e256f>:0
