### ISSUE TITLE
Simple Example of Navigation

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#54]
Hi Dan, thank you for this nice extension for Prims.

I am new to Prism, so you demo code got a little complex to me, so I am here to ask you a little help.

I`m trying to open a Page directly with the PopUp over it. Trying something like:

`NavigationService.NavigateAsync("WelcomePage/NewVersionPopupPage");`

but on iOS I got the "application wndows are expected to have a root view controller...".

I don't know if it is supposed to work that way or not.

**Comment by dansiegel** [comment]
does it work if you navigate to each one separately?

**Comment by cassionandi** [comment]
The WelcomePage opens if alone in the NavigateAsync. The PopupPage dont. Together pages don't open too.

Just to be clear, this is in the App.cs, opening the first page of the app.

**Comment by dansiegel** [comment]
ok, but if you are on WelcomPage andyou have `_navigationService.NavigateAsync("NewVersionPopupPage")` does that work or fail...

**Comment by cassionandi** [comment]
It works (but then we have the problem of the other Issue #52) where the Popup is opening like a normal page, not a overlay popup.

**Comment by dansiegel** [comment]
@cassionandi I’m aware of that issue please continue to track it there
