### ISSUE TITLE
Error registering Prism.Navigation.INavigationService

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#62]
On version 2.0.0-pre5, when the App start it shows:

`Unable to resolve Prism.Navigation.INavigationService {ServiceKey="PageNavigationService"}
  from container
  with normal and dynamic registrations:
  DefaultKey(0), {ID=98, ImplType=Prism.Plugin.Popups.PopupPageNavigationService}}`

Registering like the docs says:
`            containerRegistry.RegisterPopupNavigationService();
`
I'm using DryIoC on .net 2.0

**Comment by dansiegel** [comment]
Crap... I specifically tested this too. I’ll try to get this resolved ASAP.

**Comment by cassionandi** [comment]
@dansiegel do you need some log or sample code that I can provide?

**Comment by dansiegel** [comment]
No I reproduced it pretty quick... I just need to be able to dedicate the debug time.

**Comment by dansiegel** [comment]
This is fixed in pre6...
