### ISSUE TITLE
Open Popup onNavigatedTo

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#63]
Hi!

It is possible to open a Popup when the page finishes to load (onNavigatedTo) ?

My page is opened like this:

`NavigationService.NavigateAsync("NavigationPage/WelcomePage");`

When it finishes load, I would like to popup a page to the user. I am doing this:

` if (condition)
            {
                await _navigationService.NavigateAsync("WarningPopupPage");
            }`

This isn't working...

**Comment by cassionandi** [comment]
on iOS it doesn't show the Popup (its like nothing happened).

on Android it shows an empty Popup this the image:
![image](https://user-images.githubusercontent.com/699167/37341559-95e875a6-26a0-11e8-99f0-6cf74a8f883e.png)

**Comment by cassionandi** [comment]
if I remove the "NavigationPage", on android it works...

**Comment by dansiegel** [comment]
can you send me a repro

**Comment by cassionandi** [comment]
Will try to get a sample from my main project.

**Comment by cassionandi** [comment]
@dansiegel sorry for the delay

Here is a repo with a Sample code. Works on Android Emulator, but not on iOS Simulator. 

https://github.com/cassionandi/PopupSample

I have to say that it is not the fully scenario of my App, but maybe solving this I can apply it to my full app too.

**Comment by dansiegel** [comment]
looking at your code you're trying to push the popup page before the page has been pushed onto the NavigationStack which is why you're having problems.

You could try moving the Navigation to `OnNavigatedTo` which is triggered after the page is pushed onto the NavigationStack.... or you could implement `IPageLifecycleAware` and push it when `OnAppearing` is fired.

**Comment by cassionandi** [comment]
@dansiegel Prism 7 is really killer, it has everything needed for my project for now. 
Did not know about `IPageLifecycleAware`, thank you for your advice.
