### ISSUE TITLE
Last versions and NavigationService

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#65]
hi @dansiegel 

I've updated all nugets and now I can't open a Popup "alone" without another page on the background.

`NavigationService.NavigateAsync("MainPage/PopupPageA/PopupPageB");`

Something like the code above don't work on iOS, but if I open the MainPage and after open the PopupPageA it works.

This is the only message showed:
`2018-04-06 10:53:38.849 AppNovo.iOS[17494:594432] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.52.10/UIApplication.m:3538`

Versions 
Xamarin.Forms 2.5.1.444934
Rg.Plugins.Popup 1.1.4.145-pre
Prism.Plugin.Popups 2.0.0.528-pre

**Comment by dansiegel** [comment]
To the best of my knowledge that is expected behavior... either way it isn't an issue with the Prism Plugin.
