### ISSUE TITLE
Prism.Plugin.Popups logo

### ISSUE THREAD

**Issue by reallinfo** [dansiegel/Prism.Plugin.Popups#69]
Hello, Do you need a logo for prism? If there is your a logo idea, I would like to hear it.

**Comment by reallinfo** [comment]
Do you have an idea? Or I can design a logo very soon ?

**Comment by reallinfo** [comment]
Hello @dansiegel What's going on?

I desgined a few logo? How do these look?

![prism](https://user-images.githubusercontent.com/36298335/40928701-f4b05ff6-682a-11e8-8d14-576706f51397.jpg)

**Comment by dansiegel** [comment]
I really want to incorporate the Prism logo

**Comment by reallinfo** [comment]
I do not quite understand what you mean. Any other ideas? We can design something together.

**Comment by lewcianci** [comment]
@reallinfo WIthout being able to read @dansiegel's mind, I think he means he wants to incorporate the existing Prism logo into whatever is the Prism popup's logo.

You can see the prism logo from the bottom right of this picture.  I think this is the current Prism logo.

![image](https://user-images.githubusercontent.com/9065229/46911516-99187000-cfa1-11e8-9fe3-c33b7f3d3f53.png)

**Comment by dansiegel** [comment]
@reallinfo sorry this issue got away from me here. Yes as @lewcianci mentioned, what I'm looking for is to incorporate the Prism logo

**Comment by dansiegel** [comment]
closing as stale
