### ISSUE TITLE
Prism.Plugin.Popups 1x : getting unity error for IOS

### ISSUE THREAD

**Issue by Tanim3k** [dansiegel/Prism.Plugin.Popups#71]
I am getting this error when trying to build after included popup 1x, -
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(791,3): error : Can't resolve the reference 'Microsoft.Practices.Unity.IUnityContainer', referenced from the method 'Microsoft.Practices.Unity.IUnityContainer Prism.Navigation.PopupExtensions::get_s_container()' in 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'.

**Comment by dansiegel** [comment]
you're likely trying to mix Prism 7 with v1 of the plugin... use v2... I cannot release it as stable until Rg.Plugins.Popup releases a "Stable" package....
