### ISSUE TITLE
ClearPopupStackAsync closes only one popup (not all)

### ISSUE THREAD

**Issue by RadoslawKubas** [dansiegel/Prism.Plugin.Popups#75]
ClearPopupStackAsync result is not success and only one popup is closed. The reason is because it calls 

`var result = await navigationService.GoBackAsync(parameters, animated: animated);`

but override method in PopupPageNavigationService is 

`public override async Task<INavigationResult> GoBackAsync(INavigationParameters parameters)`

so version with "animated" is not overridden.

**Comment by dansiegel** [comment]
fixed in 2.2
