### ISSUE TITLE
Clearing the Popup Stack should not be animated

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism.Plugin.Popups#79]
Unfortunately closing issue was too fast. I just tested new version in my solution and it still not working.

ns.NavigateAsync("Page1");
ns.NavigateAsync("PopupA");
ns.NavigateAsync("PopupB");
ns.NavigateAsync("PopupC");
ns.ClearPopupStackAsync();

It closes only one, the last popup and again inside "while" loop "result.Success" is false. Same behavior as before.

I noticed one more thing, since there is "await" inside loop, even if it works, popups are not closed simultaneously, but one by one. When there is closing animation it is not expected behavior. It would be better if all closing animations were playing simultaneously (like when you open more popups and CloseWhenBackgroundIsClicked="True").

_Originally posted by @RadoslawKubas in https://github.com/dansiegel/Prism.Plugin.Popups/issues/75#issuecomment-443159917_

**Comment by RadoslawKubas** [comment]
Small clarification... ns.ClearPopupStackAsync(animated:false) works as expected, without disappearing animation. More important would be (if possible) to start all popup animations in same time. It would be perfect if it works exactly as it works in case CloseWhenBackgoundIsClicked event (as mentioned before). If more than one popup is opened and all of them has property CloseWhenBackgroundIsClicked="True" and BackgroundInputTransparent="True" than when you tap background all popups close very nice simultaneously with animations.

**Comment by dansiegel** [comment]
this should actually be fixed in the latest release
