### ISSUE TITLE
ClearPopupStackAsync throw exception

### ISSUE THREAD

**Issue by RadoslawKubas** [dansiegel/Prism.Plugin.Popups#80]
### Description
ClearPopupStackAsync always throw exception and close only one opened popup.

It seems that problem is as I described in #75.

> The reason is because it calls
>
>var result = await navigationService.GoBackAsync(parameters, animated: animated);
>
>but override method in PopupPageNavigationService is
>
>public override async Task<INavigationResult> GoBackAsync(INavigationParameters parameters)
>
>so version with "animated" is not overridden.

Simple overriding also method with parameters not working in this case because GoBackAsync with more parameters is static INavigationServiceExtensions method, so can't be override. I created PR with some fix proposition before (#76) (this fix works, and even if is not good way to fix it, show where is the problem)
 
### Steps to Reproduce
1. Open 2 popups  
`NavigationService.NaviageAsync("PopupA"); 
NavigationService.NavigateAsync("PopupB");` 
2. Execute
`NavigationService.ClearPopupStackAsync()`

### Expected Behavior
All popups are closed with animation. 

[issue80expected.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/2671729/issue80expected.zip)

### Actual Behavior
Only one popup is closed and throws System.NullReferenceException (in result) at PopupPageNavigationService.

[issue80.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/2671725/issue80.zip)

### Basic Information
- Version with issue: 2.2.0.293
- Last known good version: -

### Reproduction link
https://github.com/RadoslawKubas/PrismPluginPopupsProblem

**Comment by dbelz** [comment]
Any news on this topic? We are having the same problem.

**Comment by dansiegel** [comment]
I haven't been able to reproduce this issue.
