### ISSUE TITLE
Navigating to other page close opened popups after navigation finish.

### ISSUE THREAD

**Issue by RadoslawKubas** [dansiegel/Prism.Plugin.Popups#81]
### Description
Navigation to other page if there are some open popups is closing all of them (what is nice) but it would be better to close them when the page transition starts (not after finish) and if possible with closing animation. 
 
### Steps to Reproduce
1. Open 2 popups  
`NavigationService.NaviageAsync("PopupA"); 
NavigationService.NavigateAsync("PopupB");` 
2. Execute
`NavigationService.NavigateAsync("PageA")`

### Expected Behavior
All popups are closed with animation and animation starts when page transition animation starts (or at least popups closed without animation but just after transition animation starts). 

[issue81expected.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/2671736/issue81expected.zip)

### Actual Behavior
All popups are closed without animation after page transition animation finish.

[issue81.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/2671737/issue81.zip)

### Basic Information
- Version with issue: 2.2.0.293
- Last known good version: -

### Reproduction link
https://github.com/RadoslawKubas/PrismPluginPopupsProblem

**Comment by dansiegel** [comment]
this issue should be resolved. Note that it will only animate if the animate bool is true.
