### ISSUE TITLE
Popup not display when navigate from Master Page

### ISSUE THREAD

**Issue by dienbien001** [dansiegel/Prism.Plugin.Popups#83]
Your works is awesome, it's work great for almost all place of my project, except when i call from my Master Page.
The code as below:
My Master Page:

```
<MasterDetailPage.Master>
        <ContentPage Title="Master">
            <Button Text="Display popup" Command="{Binding DisplayPopupCommand}" />
        </ContentPage>
</MasterDetailPage.Master>
```

Method on my ViewModel:
```
private void DisplayPopup()
{
      NavigationService.NavigateAsync("PopupPage");
}
```
Method DisplayPopup is called, but the popup not display. I've added containerRegistry.RegisterPopupNavigationService() to my App.xaml.cs.
If i changed my button to use Clicked event and call event handle, it's work fine:
```
private void Button_OnClicked(object sender, EventArgs e)
        {
            Navigation.PushPopupAsync(new PopupPage());
        }
```

I wonder if there is any way to solve this problem?
Thank you very much.

**Comment by danilkurkin1** [comment]
@dienbien001 Did you managed to come across this issue?
Have same problem where  await _navigationService.NavigateAsync("PopupPage");
doesn't do anything

**Comment by danilkurkin1** [comment]
@dienbien001 & everyone looking at this issue => When using Prism Templates for Popup, ViewModel constructor set to PROTECTED. Once it is changed to PUBLIC - popup is loading as it should.

**Comment by dienbien001** [comment]
> @dienbien001 & everyone looking at this issue => When using Prism Templates for Popup, ViewModel constructor set to PROTECTED. Once it is changed to PUBLIC - popup is loading as it should.

My PopupPage just display a label, so i dont use ViewModel for it.
Could you take a look at my sample: https://github.com/dienbien001/PrismPluginPopupSample
Thank you very much.

**Comment by danilkurkin1** [comment]
@dienbien001 did you check if your command got hit? could be binding issues between your view and ViewModel for MainPage.
Also use nav service you are reciving via constructor 


public MainPageViewModel(INavigationService navigationService)
            : base(navigationService)
        {
            Title = "Main Page";
           _navigationService = navigationService;
        }

         private void DisplayPopup()
        {
            _navigationService.NavigateAsync("PopupPage");
        }

**Comment by dienbien001** [comment]
> @dienbien001 did you check if your command got hit? could be binding issues between your view and ViewModel for MainPage.
> Also use nav service you are reciving via constructor
> 
> public MainPageViewModel(INavigationService navigationService)
> : base(navigationService)
> {
> Title = "Main Page";
> _navigationService = navigationService;
> }
> 
> ```
>      private void DisplayPopup()
>     {
>         _navigationService.NavigateAsync("PopupPage");
>     }
> ```

Yes the command got hit.

**Comment by mzhukovs** [comment]
Does this work for you @dienbien001 :
_navigationService.NavigateAsync("NavigationPage/PopupPage");

For me, @dansiegel , on Android and UWP the popup is coming up fine from my MasterDetail menu, and on iOS too, HOWEVER, shortly after the popup appears, with no further action, an exception gets thrown a couple of seconds later: **System.InvalidOperationException: Cannot remove root page when it is also the currently displayed page.**

And it only happens on iOS. Again on Android and UWP totally fine. It's strange because literally no other code/user interaction takes place after navigating to the popup and then BAM. 

Any ideas? Advice would be much appreciated. Let me know if need additional details.

**Comment by dansiegel** [comment]
This fix will be in the next release. Note that you will need to update to Prism 7.2.
