### ISSUE TITLE
Not finding method PushPopupPageAsync

### ISSUE THREAD

**Issue by MohDotNet** [dansiegel/Prism.Plugin.Popups#85]
Good Day,

So i am using Xamarin, with Prism.  I have also installled the Prism.Plugins and followed the documentation how ever 

i do not see this method 
PushPopupPageAsync

when i go... naigationService.
 
kindly advise why am i not seeing it.
oh yes rg.plugins.popus is installed aswelled.

kind regards
Mohamed.

**Comment by dansiegel** [comment]
@mohamedDotNet can you please provide a sample that reproduces the issue.

**Comment by stephenhauck** [comment]
I needed this today and found the same issue.
So I made a template app using VS 2017 Enterprise and added the registration code but still not showing for me either ..
![image](https://user-images.githubusercontent.com/12648793/55833672-b310b680-5add-11e9-827b-e5a826967cea.png)

![image](https://user-images.githubusercontent.com/12648793/55833684-bc9a1e80-5add-11e9-8499-3f5161f0770e.png)


![image](https://user-images.githubusercontent.com/12648793/55833581-793fb000-5add-11e9-9833-a8760383a7dc.png)

**Comment by stephenhauck** [comment]
OK, just to make sure I made a new app from the template installed for VS 2017
When it added Prism.Plugin.Popups it did not show in NuGet list so I manually added it then recompiled ..
![image](https://user-images.githubusercontent.com/12648793/55834874-77c3b700-5ae0-11e9-957c-f4494afefac1.png)

It's still not showing 
![image](https://user-images.githubusercontent.com/12648793/55834934-9f1a8400-5ae0-11e9-9c8c-7312ee7837e3.png)

**Comment by dbelz** [comment]
Because the 2 methods are deprecated as written on the readme page.

**Comment by dansiegel** [comment]
this is not an issue as the methods requested no longer is supported. Just use NavigateAsync.
