### ISSUE TITLE
Clearing the navigation history, without using the "app:///NavigationPage/"

### ISSUE THREAD

**Issue by KSemenenko** [dansiegel/Prism.Plugin.Popups#86]
I have a situation when I need to clear the navigation history. 
I found a solution to open a new page. and thereby erase history. 
But this option does not suit me, since during the creation of the page I see a white screen for a while.
Therefore, I would like to be able to simply clear the navigation stack.
Is there such an options?

**Comment by dansiegel** [comment]
Closing as Spam
